[workspace]
members = [
    "ft-sdk",
    "ft-sys",
    "ft-sys-shared",
]
resolver = "2"

[workspace.package]
authors = [
    "Amit Upadhyay <upadhyay@gmail.com>",
    "Arpita Jaiswal <arpita@fifthtry.com>",
    "Rithik Seth <rithik@fifthtry.com>",
]
edition = "2021"
description = "ft: FifthTry Backend"
license = "Copyright FifthTry"
repository = "https://github.com/FifthTry/ft"
homepage = "https://FifthTry.com"


[workspace.dependencies]
http = "1"
bytes = "1"
serde = {  version = "1", features = ["derive"] }
thiserror = "1"