[workspace]
members = [
    "ft-sdk",
    "ft-sys",
    "ft-sys-shared",
]
exclude = ["sample-sqlite", "sample-pg", "foo"]
resolver = "2"

[workspace.package]
authors = [
    "Amit Upadhyay <upadhyay@gmail.com>",
    "Arpita Jaiswal <arpita@fifthtry.com>",
    "Rithik Seth <rithik@fifthtry.com>",
]
edition = "2021"
description = "ft: FifthTry Backend"
license = "BSD-3-Clause"
repository = "https://github.com/FifthTry/ft"
homepage = "https://FifthTry.com"


[workspace.dependencies]
http = "1"
bytes = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
chrono = { version = "0.4", default-features = false, features = ["serde"] }
diesel = "2"
serde_urlencoded = "0.7"


[workspace.dependencies.rusqlite]
version = "0.31"
features = [
    # We are using bundled version of rusqlite, so we do not need sqlitelib, headers as a
    # dependency. By default, if we do not bundle, our binary will link against system
    # provided sqlite, which would have been a good thing, if we used system sqlite, our
    # binary size would be smaller, compile time lesser, but unfortunately we can not assume
    # sqlite dynamic library is installed on everyone's machine. We can choose to give two
    # binaries, one with bundled, one without, but it is not worth the tradeoff right now.
    "bundled",
    "column_decltype",
]
