[workspace]
members = [
    "ft-sdk",
    "ft-sys",
    "ft-sys-shared",
]
resolver = "2"

[workspace.package]
authors = [
    "Amit Upadhyay <upadhyay@gmail.com>",
    "Arpita Jaiswal <arpita@fifthtry.com>",
    "Rithik Seth <rithik@fifthtry.com>",
]
edition = "2021"
description = "ft: FifthTry Backend"
license = "Copyright FifthTry"
repository = "https://github.com/FifthTry/ft"
homepage = "https://FifthTry.com"


[workspace.dependencies]
acme = { package = "acme-rfc8555", git = "https://github.com/x52dev/acme-rfc8555", rev = "77f858a" }
acme-helper = { path = "acme-helper" }
acmen = { path = "acmen" }
actix-cors = "0.7.0"
actix-http = "3"
actix-multipart = "0.6"
actix-multipart-derive = "0.6"
actix-web = "4"
async-lock = "3"
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-s3 = { version = "1", features = ["rt-tokio"] }
aws-sdk-secretsmanager = { version = "1" }
base64 = "0.22"
bytes = "1"
camino = "1"
chrono = { version = "0.4", features = ["serde"], default-features = false }
colored = "2"
dashmap = "5"
deadpool = { version = "0.10" }
deadpool-postgres = "0.12"
tokio-postgres = "0.7"
diesel-async = { git = "https://github.com/weiznich/diesel_async", rev = "017ebe2", features = ["postgres", "deadpool", "async-connection-wrapper"] }
diesel_migrations = "2"
diffy = "0.3"
env_logger = "0.11"
eyre = "0.6"
fastn-core = { path = "fastn/fastn-core" }
fastn-ds = { path = "fastn/fastn-ds" }
ft-aws = { path = "ft-aws" }
ft-db = { path = "ft-db" }
ft-macros = { path = "ft-macros" }
ft-sdk = { path = "../ft-sdk/ft-sdk" }
ft-sys = { path = "../ft-sdk/ft-sys" }
ft-sys-shared = { path = "../ft-sdk/ft-sys-shared" }
hostn-wasm = { path = "hostn-wasm" }
http = "1"
ftd = { path = "fastn/ftd" }
futures = "0.3"
futures-core = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["std"] }
hickory-proto = "0.24"
hickory-resolver = "0.24"
hostn = { path = "hostn" }
include_dir = "0.7"
indoc = "2"
itertools = "0.12"
magic-crypt = { version = "3", default-features = false }
mime_guess = "2"
once_cell = "1"
pretty = "0.12"
proc-macro2 = "1"
quote = "1"
regex = "1"
reqwest = { version = "0.11", features = ["json"] }
scoped-futures = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
slug = "0.1"
snafu = "0.8"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
url = "2"
url-escape = "0.1"
lettre = { version = "0.11", features = ["serde", "tokio1", "tokio1-native-tls"] }
wasmtime = { version = "18", features = ["async"] }


[workspace.dependencies.diesel]
version = "2"
no_default_features = true
features = [
    "chrono", # diesel::sql_types::Timestamptz -> chrono::DateTime<chrono::Utc>
    "serde_json", # diesel::sql_types::Jsonb -> serde_json::Value
    "network-address" # diesel::sql_types::Inet -> ipnetwork::IpNetwork
]


[workspace.dependencies.syn]
version = "2.0"
#features = [
#    "full",
#    "parsing",
#    "printing",
#    "visit-mut",
#    "clone-impls",
#    "extra-traits",
#    "proc-macro",
#]
#default-features = false



[workspace.dependencies.fastn-observer]
git = "https://github.com/fastn-stack/fastn-observer"
rev = "5f64c7b"


[workspace.dependencies.uuid]
version = "1.6.1"
features = [
    "v4", # Lets you generate random UUIDs
    "fast-rng", # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "serde",
]

[workspace.dependencies.ipnetwork]
version = ">=0.12.2, <0.21.0"
