[workspace]
members = [
    "ft-sdk",
    "ft-sys",
    "ft-sys-shared",
]
exclude = ["sample-sqlite", "foo", ]
resolver = "2"

[workspace.package]
authors = [
    "Amit Upadhyay <upadhyay@gmail.com>",
    "Arpita Jaiswal <arpita@fifthtry.com>",
    "Rithik Seth <rithik@fifthtry.com>",
]
edition = "2021"
description = "ft: FifthTry Backend"
license = "BSD-3-Clause"
repository = "https://github.com/FifthTry/ft"
homepage = "https://FifthTry.com"


[workspace.dependencies]
http = "1"
bytes = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
chrono = { version = "0.4", default-features = false, features = ["serde"] }
diesel = "2"
serde_urlencoded = "0.7"
