[workspace]
members = [ "examples/hello-world",
    "ft-sdk",
    "ft-sys",
    "ft-sys-shared",
]
exclude = ["examples"]
resolver = "2"

[workspace.package]
authors = [
    "Amit Upadhyay <upadhyay@gmail.com>",
    "Arpita Jaiswal <arpita@fifthtry.com>",
    "Rithik Seth <rithik@fifthtry.com>",
]
edition = "2021"
description = "ft: FifthTry Backend"
license = "BSD-3-Clause"
repository = "https://github.com/FifthTry/ft"
homepage = "https://FifthTry.com"


[workspace.dependencies]
http = "1"
bytes = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
chrono = { version = "0.4", default-features = false, features = ["serde"] }
diesel = { version = "2", features = ["serde_json"] }
serde_urlencoded = "0.7"
include_dir = "0.7"
rand_core = "0.6"

[workspace.dependencies.rusqlite]
version = "0.31"
default-features = false


[workspace.dependencies.serde_sqlite_jsonb]
# we are using our own fork as the original crate does not compile again wasm
# path = "../serde-sqlite-jsonb"
package = "fifthtry-serde_sqlite_jsonb"
version = "0.1"
