[package]
name = "form-handling"  # make sure name stays in sync with build.sh
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
ft-sdk = { version = "0.1", path = "../../ft-sdk" }
http = "1"
bytes = "1"
