# Code taken from https://github.com/wyyerd/stripe-rs/tree/c2f03f8dec41e20b66f9bbe902b8384096ac653c
[package]
name = "ft-stripe"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
thiserror.workspace = true
http.workspace = true
ft-sdk.workspace = true
bytes.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true
ft-sys.workspace = true
smol_str = "0.1"
