[package]
name = "ft-sdk"
version = "0.1.2"
description = "ft-sdk: SDK for building FifthTry Applications"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
default = ["sqlite-default", "migration"]
postgres-default = ["ft-sys/postgres-default", "postgres"]
postgres = ["ft-sys/postgres", "diesel"]
sqlite-default = ["ft-sys/sqlite-default", "sqlite"]
sqlite = ["ft-sys/sqlite", "diesel"]
migration = [] # only if either sqlite-default or postgres-default is activated
auth-provider = ["uuid"]

[dependencies]
ft-sys = { path = "../ft-sys", version = "0.1.2", default-features = false }
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
thiserror.workspace = true
http.workspace = true
bytes.workspace = true
serde_urlencoded.workspace = true
diesel = { workspace = true, optional = true }
include_dir.workspace = true
rand_core.workspace = true
uuid = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions = "1"
