[package]
name = "ft-sdk"
version = "0.1.2"
description = "ft-sdk: SDK for building FifthTry Applications"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
auth-providers = []
# toggle usage of ft_sdk::println! statements
debug = []
default = ["sqlite-default"]
postgres-default = ["ft-sys/postgres-default", "postgres"]
postgres = ["ft-sys/postgres", "diesel"]
sqlite-default = ["ft-sys/sqlite-default", "sqlite"]
sqlite = ["ft-sys/sqlite", "diesel"]

[dependencies]
ft-sys = { path = "../ft-sys", version = "0.1.2", default-features = false }
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
thiserror.workspace = true
http.workspace = true
bytes.workspace = true
serde_urlencoded.workspace = true
diesel = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions = "1"
