[package]
name = "ft-sdk"
version = "0.1.1"
description = "ft-sdk: SDK for building FifthTry Applications"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true


[dependencies]
ft-sys = { path = "../ft-sys", version = "0.1.1" }
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
thiserror.workspace = true
http.workspace = true
bytes.workspace = true
serde_urlencoded.workspace = true
diesel.workspace = true
