[package]
name = "ft-sys"
version = "0.1.1"
description = "ft-sdk: SDK for building FifthTry Applications"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
http.workspace = true
bytes.workspace = true
ft-sys-shared = { path = "../ft-sys-shared", version = "0.1.0" }
chrono.workspace = true

[dependencies.diesel]
version = "2"
features = [
    "postgres_backend",
    "i-implement-a-third-party-backend-and-opt-into-breaking-changes"
]
