[package]
name = "ft-sys"
version = "0.1.0"
description = "ft-sdk: SDK for building FifthTry Applications"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
http = "1"
bytes = "1"
ft-sys-shared = { path = "../ft-sys-shared" }
chrono = { version = "0.4", default-features = false, features = ["serde"] }

[dependencies.diesel]
version = "2"
features = [
    "postgres_backend",
    "i-implement-a-third-party-backend-and-opt-into-breaking-changes"
]
